#!/bin/sh
for folder in $(ls -1 -d */)
do
	folder=$(echo $folder | sed 's/\/$//')
	echo "Installing $folder"
	stow -D $folder
	stow $folder
done

echo "Installing VSCode"
[ -f ~/Library/Application\ Support/Code/User/settings.json ] || ln -s $(PWD)/vscode-settings.json ~/Library/Application\ Support/Code/User/settings.json

echo "Installing tpm"
[ -d ~/.tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
